[[cminpack]]
arch = "aarch64"
git-tree-sha1 = "2bb0b8eae02358e93c06c6c2bebbccfd4f10f500"
os = "macos"

    [[cminpack.download]]
    sha256 = "87ba0f9aea3d024ca59681db9e6fa8b306b7c079651f0553a705ee6bed971f41"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.aarch64-apple-darwin.tar.gz"
[[cminpack]]
arch = "aarch64"
git-tree-sha1 = "8e61ab64a2297796f4b0f8867a2777620b53eb55"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "d06b788665b14195e1195e06676eba868fdcd96ed7b1b4725bf6f60bd42d480a"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.aarch64-linux-gnu.tar.gz"
[[cminpack]]
arch = "aarch64"
git-tree-sha1 = "6e5e47a4f937f31aa61179ddede332208a2aa7be"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "a2fd5ae16e4f238af7e15ca08b16214458070f03a60221437350ba974a50ca5c"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.aarch64-linux-musl.tar.gz"
[[cminpack]]
arch = "aarch64"
git-tree-sha1 = "cf0bc27eb1e6f1ba9dd0c6f579ca200caecfdc42"
os = "freebsd"

    [[cminpack.download]]
    sha256 = "0f737abfb14ea34e0f376750559409efdef4735c38b76c0f7e027eee5d3cfdc1"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.aarch64-unknown-freebsd.tar.gz"
[[cminpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a21d16d941ef95b4d7e692336717529867f9cead"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "e0c1747199b2b628e8de895bb7b05733d534ec933575aef932ca55c3da68dcb1"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.armv6l-linux-gnueabihf.tar.gz"
[[cminpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b4292e828d7114df589388ac08f2aeaa177b3eec"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "9095af1faca530588c060ce6f763ba95fb80513a2b23f7b2c2b3adaa0f27d59f"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.armv6l-linux-musleabihf.tar.gz"
[[cminpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b283040c3348ba4b5ffffcc708a03598bd294cd8"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "8e2fbc287d0d370597e82e8ca53368abb62e43c80aec51bff5c18103dc08656a"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.armv7l-linux-gnueabihf.tar.gz"
[[cminpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "710cb9f1e6a127e829791cf3cb41527008798a87"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "4bf7c477fc6f308cb98aede48a78b59608e809aeb2da9d6d54d0fdc968ab97dc"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.armv7l-linux-musleabihf.tar.gz"
[[cminpack]]
arch = "i686"
git-tree-sha1 = "c658ba5a7d18fdf75aed72f9569d62d9d03c590c"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "555b46860c8b9a5808887b41b6cc15aa0909418732dd821bbd6334d5ba79dd51"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.i686-linux-gnu.tar.gz"
[[cminpack]]
arch = "i686"
git-tree-sha1 = "db2a7511c3eacb7b5ffb7a477f588aaff08dc236"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "9a6046bf411b47801965a24265b43a6512802aa02550a945b52c003b2e8e053e"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.i686-linux-musl.tar.gz"
[[cminpack]]
arch = "i686"
git-tree-sha1 = "631fdfea97e76c2716bc20101e9685107ad35dd1"
os = "windows"

    [[cminpack.download]]
    sha256 = "4c439021dc1aa93a75999592debc3bb829c62ecc45f2fdd5fe5de2f8d765700d"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.i686-w64-mingw32.tar.gz"
[[cminpack]]
arch = "powerpc64le"
git-tree-sha1 = "5485ae4e3e0e812221f76a58019f19eeed72e6c9"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "a885fa8c3a723408c72f1c590150e774119b8e833e16e5ad0c52167b34985ae2"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.powerpc64le-linux-gnu.tar.gz"
[[cminpack]]
arch = "riscv64"
git-tree-sha1 = "b4ac80fb25892399441deef59a81bb2a1bdd75f1"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "9fbd5774de1ba5d027ba58cd680cb192fed0d543d74275c544dd8b015f8aa469"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.riscv64-linux-gnu.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "c80880cf77f53ec3a6ea1c08ae7f065383a237bd"
os = "macos"

    [[cminpack.download]]
    sha256 = "a80c01f69f2a1ac979bef00a899972032072db326fae76a3f904b53de86fd473"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.x86_64-apple-darwin.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "9e8d05cecb2621d8459dedd66979df02861695dd"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "c8e0bf5f2c5209434d31c56ad3370e7281c46bfbe750426356c719fe8477e5bd"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.x86_64-linux-gnu.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "340f3eff51401d54afb5e5ba4d0a8d4456f85a69"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "818bb8197f93157c429b4183e7d01137d6c1d9fcb6a516e7d9cb4d196e6fa54c"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.x86_64-linux-musl.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "a4c1ef7f84d91b2be77de863e9a9126fc8f9e227"
os = "freebsd"

    [[cminpack.download]]
    sha256 = "a461bf33bb6a4b3a4c4c97ef33ffa8a9c85f8867e6a52cafed529eb6acce7acf"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.x86_64-unknown-freebsd.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "11f7f510fe7bf78f00d0c8b01ee49be4878528d5"
os = "windows"

    [[cminpack.download]]
    sha256 = "893d7a92cc15d6c415b467c32fc2976bcfec4c189793e574f4ce89285e0676f2"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.11+0/cminpack.v1.3.11.x86_64-w64-mingw32.tar.gz"
