[[cminpack]]
arch = "aarch64"
git-tree-sha1 = "7c2eb94138d929bf3b5ea0a6756f2e0e37ff406b"
os = "macos"

    [[cminpack.download]]
    sha256 = "daabbd3413eacdde2bd246b7d5626874d6d4f267f747e7e6ac72636873d20b09"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.aarch64-apple-darwin.tar.gz"
[[cminpack]]
arch = "aarch64"
git-tree-sha1 = "a0e8ac35c9855572167e89eff30a90b99d2fe6f7"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "38a5e149bde4ff162a5b76b0ef2ab03125cf33abbd72a35f3df3abc4a3c90eee"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.aarch64-linux-gnu.tar.gz"
[[cminpack]]
arch = "aarch64"
git-tree-sha1 = "0425778eb7da5fa93b8742a18ccbc94971ee9928"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "0d0ae69ff48a40916d064ebf0e1be048adeef3bded2dafac8546a1b133503952"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.aarch64-linux-musl.tar.gz"
[[cminpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4034e5aebb6c16cf2e5ee95925224cf5ce8b7e17"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "eabbba04e541f1fcbde181520ad186e898f35aeb6e82b909b9dc24871ef6a8cb"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.armv6l-linux-gnueabihf.tar.gz"
[[cminpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4ee5d9505f6bd4c824d5974cce269a771c10377"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "c2c95dd060c49d2378645e01c36946ae87931e7c695857858fbcb712c7baa7bc"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.armv6l-linux-musleabihf.tar.gz"
[[cminpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0fa4dc9a4f3636ace62112be900c8da754bf1861"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "885e54b8653b7830579b809acaf1a2ae694007a91aaf4b2559e5ad09514defef"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.armv7l-linux-gnueabihf.tar.gz"
[[cminpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75eb6bfcf49623e5763c48c948afd0db5b8ece9f"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "53f3ecb956502e59b5b022ca9f0e0c6cd71aaf0850d88f8b1366e55f134bde4a"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.armv7l-linux-musleabihf.tar.gz"
[[cminpack]]
arch = "i686"
git-tree-sha1 = "efd29e888c65b8103a6466ef226e402521c37e88"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "f6abdbd2e69eb3177016a7c49578b4983e97c6339fbc0413de64495177932592"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.i686-linux-gnu.tar.gz"
[[cminpack]]
arch = "i686"
git-tree-sha1 = "d1c2d47b84ec932a5f08cad39969856cf9f4b14c"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "f8e3adb64ec8dcd6d221b04c30b85076549033d8e4d989466915f097d0daacf7"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.i686-linux-musl.tar.gz"
[[cminpack]]
arch = "i686"
git-tree-sha1 = "ba688d85e2e653bfa186046ad6611dc532f4f69a"
os = "windows"

    [[cminpack.download]]
    sha256 = "623f6513313cc5e1fc29db8ed8f23b1db32b947217d9518bf9ebd7c21cfbc1dc"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.i686-w64-mingw32.tar.gz"
[[cminpack]]
arch = "powerpc64le"
git-tree-sha1 = "f62580a4ac7ea4a3f524390b47b8975851fbec3d"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "06620deaa1a17cd22790a5615f49815773672e952b53864c68270fc17377d0e9"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.powerpc64le-linux-gnu.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "d93b1bc756c0899c2d231c80f18fef0662fb2493"
os = "macos"

    [[cminpack.download]]
    sha256 = "8648bf400c8a94c76f81dc5430e693ccd48310c02b24dfeb7e6695b063c438a6"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.x86_64-apple-darwin.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "4d0e44d1c4ff94eb9ae134a822fe7a6f31e75c21"
libc = "glibc"
os = "linux"

    [[cminpack.download]]
    sha256 = "69bd6a8f86014ca97a2b24b2ae06445e2e35baa77bea8e9ee35a43ccd04a0049"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.x86_64-linux-gnu.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "e8204d3f32af54a183dee58ba3347d0cf81ed790"
libc = "musl"
os = "linux"

    [[cminpack.download]]
    sha256 = "2da4d5e8291e44edcdf02021d3ebd049fb1623294150b0c3cf2137a73cc175e6"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.x86_64-linux-musl.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "1b8d216777a0c146717de0465eacee00f4790784"
os = "freebsd"

    [[cminpack.download]]
    sha256 = "07876070702e2c832c46ebc2863f7c93516da84b45d9bc66e3290d3498c1d1cc"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.x86_64-unknown-freebsd.tar.gz"
[[cminpack]]
arch = "x86_64"
git-tree-sha1 = "5322e464fa84fcde46b332a6fbd941c085551a9d"
os = "windows"

    [[cminpack.download]]
    sha256 = "9b273b08a8ac929f773992bc382a94cf3ba9533ae08344a3ef7400603c6af352"
    url = "https://github.com/JuliaBinaryWrappers/cminpack_jll.jl/releases/download/cminpack-v1.3.9+0/cminpack.v1.3.9.x86_64-w64-mingw32.tar.gz"
