# Autogenerated wrapper script for cminpack_jll for aarch64-apple-darwin-libgfortran5
export libcminpack, libcminpacks

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("cminpack")
JLLWrappers.@declare_library_product(libcminpack, "@rpath/libcminpack.1.dylib")
JLLWrappers.@declare_library_product(libcminpacks, "@rpath/libcminpacks.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libcminpack,
        "lib/libcminpack.1.3.11.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcminpacks,
        "lib/libcminpacks.1.3.11.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
