# Autogenerated wrapper script for cminpack_jll for i686-w64-mingw32-libgfortran3
export libcminpack, libcminpacks

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("cminpack")
JLLWrappers.@declare_library_product(libcminpack, "libcminpack.dll")
JLLWrappers.@declare_library_product(libcminpacks, "libcminpacks.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libcminpack,
        "bin\\libcminpack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcminpacks,
        "bin\\libcminpacks.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
