# Autogenerated wrapper script for cminpack_jll for x86_64-w64-mingw32
export libcminpack, libcminpacks

JLLWrappers.@generate_wrapper_header("cminpack")
JLLWrappers.@declare_library_product(libcminpack, "libcminpack.dll")
JLLWrappers.@declare_library_product(libcminpacks, "libcminpacks.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcminpack,
        "bin\\libcminpack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcminpacks,
        "bin\\libcminpacks.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
